{{- if and .Values.jellyfin.database.enabled (eq .Values.jellyfin.database.type "postgres") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jellyfin.database.postgresSecret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
